# Generated by Django 5.2.1 on 2025-05-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addhorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horseName', models.DateField()),
                ('horseAge', models.PositiveIntegerField()),
            ],
        ),
    ]
