# Generated by Django 5.2.1 on 2025-05-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_addhorse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addhorse',
            name='horseName',
            field=models.CharField(),
        ),
    ]
