# Generated by Django 5.2.1 on 2025-05-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_addhorse_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='horse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.addhorse'),
        ),
    ]
