# Generated by Django 5.2.1 on 2025-05-30 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_workout_horse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='tracker.addhorse'),
        ),
    ]
