# Generated by Django 5.2.1 on 2025-06-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_workout_horse'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='track_condition',
            field=models.CharField(choices=[('dry', 'Dry'), ('wet', 'Wet')], default='dry', max_length=10),
        ),
    ]
