# Generated by Django 5.2.1 on 2025-06-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_workout_track_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='wrapped',
            field=models.CharField(choices=[('cottonwrapper', 'Cotton Wrapped'), ('vettape', 'Vet Wrap Tape'), ('none', 'Not Wrapped')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='track_condition',
            field=models.CharField(choices=[('dry', 'Dry/Hard'), ('wet', 'Wet/Muddy'), ('good', 'Perfect')], default='dry', max_length=10),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('trot', 'Trot'), ('gallop', 'Gallop'), ('lope', 'Fast Gallop'), ('lightbreeze', 'Light Breeze'), ('fullsprint', 'Full Sprint')], max_length=20),
        ),
    ]
