# Generated by Django 5.2.1 on 2025-06-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_workout_wrapped_alter_workout_track_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addhorse',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='horse_images/'),
        ),
    ]
