# Generated by Django 5.2.1 on 2025-07-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_addhorse_profile_pic_addrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrace',
            name='name_of_race',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
