# Generated by Django 5.2.1 on 2025-07-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_addrace_name_of_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrace',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
